services:
  system-estv:
    build:
      context: ./system-estv
    container_name: system-estv
    restart: unless-stopped
    expose:
      - "8080"
    volumes:
      - /proc:/proc:ro
      - /sys:/sys:ro
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
